name: Check events
on:
  release:
    types:
      - released
      - prereleased

jobs:
  release_check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Verify events
        run: |
          # if the release is a prerelease
          if [ "${{ github.event.release.prerelease }}" == "true" ]; then
            echo "Prerelease"
          else
            echo "release!!"
          fi
